baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Sam Tate | Web and Voice Development in NC"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "Raleigh, NC"
author = ""
copyright = ""
description = "This is meta description"
email = "sam@tangolegal.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "images/logo.png"
phone = "Email Preferred"
theme_color = "#3d5a80"
[params.contact]
enable = false
form_action = ""
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.linkedin.com/in/samuel-a-tate/"
icon = "ti-linkedin"
[[params.social]]
URL = "https://twitter.com/tangolegal"
icon = "ti-twitter-alt"
[[params.social]]
URL = "https://www.facebook.com/tangolegal"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.instagram.com/tangolegal/"
icon = "ti-instagram"
